server:
  port: 8003


#spring:
#  datasource:
#    type: com.zaxxer.hikari.HikariDataSource
#    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#    url: 'jdbc:log4jdbc:oracle:thin:@hostname:port:Oracle sid'
#    username: 'username'
#    password: 'password'